server:
  port: 80
  servlet:
    context-path: /

spring:
  profiles:
    include: dev
  servlet:
    multipart:
      max-request-size: 20480MB
      max-file-size: 2048MB

  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:xml/*.xml   #xml扫描
  type-aliases-package: com.docker.model  #resultType 实体类映射

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true